apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-three
  labels:
    app: server-three-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-three-prod
  template:
    metadata:
      labels:
        app: server-three-prod
    spec:
      containers:
        - name: server-three-prod
          image: shubham3344/backend_server
          env:
            - name: SERVER
              value: 'three'
            - name: SERVER_ENV
              value: 'production'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-three
spec:
  selector:
    app: server-three-prod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


